# Generated by Django 6.0.5 on 2026-05-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('frozen', 'Заморожена'), ('rework', 'На доработке'), ('resolved', 'Решена'), ('closed', 'Закрыта')], default='new', max_length=15, verbose_name='Статус'),
        ),
    ]
